config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  root 'homes#index'

  post "json/departments/get_departments" => "departments#get_departments"
  post "json/users/get_users" => "users#get_users"
  post "json/package_types/get_package_types" => "package_types#get_package_types"
  post "json/inbounds/get_inbounds" => "inbounds#get_inbounds"

  get 'get_monthly_statistic' => "homes#get_monthly_statistic"

    resources :homes do 
      collection do
        get :unprocessed
        get :unprocessed_under_2_days
        get :unprocessed_2_5_days
        get :unprocessed_over_5_days
      end
    end
    resources :outbonds
    resources :inbounds do
      member do
        get :forward
        get :receive
      end
    end
    resources :internal_couriers
    resources :urgent_levels
    resources :with_couriers
    resources :delivereds
    resources :faileds
    resources :couriers
    resources :companies
    resources :users
    resources :user_groups
    resources :departments
    resources :controller_models
    resources :action_models
    resources :package_statuses
    resources :package_types
    resources :inbound_statuses
    resources :buildings
end

app/models/delivered.rb
class Delivered < ActiveRecord::Base
	belongs_to :internal_courier

	belongs_to :building
end

app/controllers/delivereds_controller.rb
class DeliveredsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorize_user

  def index
    if current_user.building
      @delivereds = Delivered.where("building_id = ?", current_user.building_id).order("created_at DESC")
    else
      @delivereds = Delivered.order("created_at DESC")
    end
  end

  def new
    @delivered = Delivered.new
    if current_user.building
      @internal_couriers = current_user.building.internal_couriers
      @inbounds = Inbound.where(inbound_status: 2, building_id: current_user.building_id)
    else
      @internal_couriers = InternalCourier.all
      @inbounds = Inbound.where(inbound_status: 2)
    end
      
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @inbounds }
    end
  end

  def show
    @delivered = Delivered.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @inbounds }
    end
  end
  
  def create
    @delivered = Delivered.new(delivered_params)
    internal_couriers = InternalCourier.find(params[:delivered][:internal_courier_id])
    @delivered.courier_name = internal_couriers.name

    if current_user.building
      @internal_couriers = current_user.building.internal_couriers
      @inbounds = Inbound.where(inbound_status: 2, building_id: current_user.building_id)
    else
      @internal_couriers = InternalCourier.all
      @inbounds = Inbound.where(inbound_status: 2)
    end

    respond_to do |format|
      if @delivered.save 
        id_inbounds = params[:inbounds]
        id_inbounds.each do |id|
          inbound = Inbound.find(id)
          inbound.delivered_id = @delivered.id
          inbound.delivered_date = @delivered.delivered_date
          inbound.delivered_time = @delivered.delivered_time
          inbound.inbound_status = 3
          inbound.save
        end

        format.html { redirect_to(delivereds_path, :notice => 'Delivered was successfully created.') }
        format.xml  { render :xml => @delivered, :status => :created, :delivered => @delivered }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @delivered.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def edit
    @inbound = Inbound.find(params[:id])
    if current_user.building
      @internal_couriers = current_user.building.internal_couriers
      @inbounds = Inbound.where(inbound_status: 2, building_id: current_user.building_id)
    else
      @internal_couriers = InternalCourier.all
      @inbounds = Inbound.where(inbound_status: 2)
    end

      @inbound_number = @inbound.inbound_number
  end
  
  def update
    @inbound = Inbound.find(params[:id])
    if current_user.building
      @internal_couriers = current_user.building.internal_couriers
      @inbounds = Inbound.where(inbound_status: 2, building_id: current_user.building_id)
    else
      @internal_couriers = InternalCourier.all
      @inbounds = Inbound.where(inbound_status: 2)
    end

    @inbound_number = @inbound.inbound_number

    respond_to do |format|
      if @inbound.update_attributes(delivered_params)        
        format.html { redirect_to(inbound_path(@inbound), :notice => 'Inbound was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @inbound.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @inbound = Inbound.find(params[:id])
    @inbound.destroy

    respond_to do |format|
      format.html { redirect_to(:controller => 'inbounds') }
      format.xml  { head :ok }
    end
  end

  private
  def delivered_params
    params.require(:delivered).permit(:delivered_date, :delivered_time, :receiver_name, :internal_courier_id, :building_id)
  end
end

app/helpers/delivereds_helper.rb
module DeliveredsHelper
end

app/views/delivereds/_form.html.erb
<%= form_for(@delivered, html: {class: "form-horizontal", role: "form"}) do |f| %>
  <% if @delivered.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@delivered.errors.count, "error") %> prohibited this inbound from being saved:</h2>

      <ul>
      <% @delivered.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:action] == "new" %>
      <%= f.hidden_field :created_by, :value => current_user.id %>
    <% else %>
      <%= f.hidden_field :updated_by, :value => current_user.id %>
    <% end %>

    <% if current_user.building %>
      <%= f.hidden_field :building_id, :value => current_user.building_id %>
    <% end %>

  <fieldset>
      <legend>Paket</legend>
      <div class="form-group">
        <label class="col-sm-3 control-label" for="date">
          Tanggal Diterima
        </label>
        <div class="col-sm-7">
          <div class="col-sm-6 padding-left-0">
            <input name="delivered[delivered_date]" value="<%= @delivered.delivered_date %>" class="col-sm-3 form-control format-datepicker" placeholder="choose the date here .." type="text">
          </div>
          <div class="col-sm-6 padding-right-0">
            <input type="text" name="delivered[delivered_time]" value="<%= @delivered.delivered_time %>" id="timepicker-default" class="col-sm-3 form-control" placeholder="choose the time here ..">
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <label class="col-sm-3 control-label" for="idfield">
          Internal Courier Name
        </label>
        <div class="col-sm-7">
          <%= f.select :internal_courier_id, options_from_collection_for_select(@internal_couriers, "id", "name", @delivered.internal_courier_id), {include_blank: "-- Pilih Internal Kurir --"}, {class: "js-example-placeholder-single js-states form-control"} %>
        </div>
      </div>  

      <div class="form-group">
        <label class="col-sm-3 control-label" for="idfield">
            Paket
        </label>
        <div class="col-sm-7">
            <select name='inbounds[]' multiple class="js-example-basic-multiple js-states form-control">
              <% @inbounds.each do |inbound| %>
                <option value="<%= inbound.id %>"><%= inbound.awb_number %></option>
              <% end %>
            </select>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-3 control-label" for="idfield">
          Penerima
        </label>
        <div class="col-sm-7">
          <input name="delivered[receiver_name]" value="<%= @delivered.receiver_name %>" class="col-sm-3 form-controlr"type="text">
        </div>
      </div>  

    </fieldset>
    <div class="form-group margin-bottom-0">
      <div class="col-sm-offset-3 col-sm-9">
        <button type="submit" class="btn btn-primary margin-left-15">
          Submit
        </button>
      </div>
    </div>
<% end %>

<%= content_for :css do %>
  
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link href="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<% end %>

<%= content_for :js do %>
    
    <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <script src="/vendor/ckeditor/ckeditor.js"></script>
    <script src="/vendor/ckeditor/adapters/jquery.js"></script>
    <script src="/vendor/jquery-validation/jquery.validate.min.js"></script>

    <script src="/vendor/maskedinput/jquery.maskedinput.min.js"></script>
    <script src="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <script src="/vendor/autosize/autosize.min.js"></script>
    <script src="/vendor/selectFx/classie.js"></script>
    <script src="/vendor/selectFx/selectFx.js"></script>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
    <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
  
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/form-validation.js"></script>
    <script src="/assets/js/form-elements.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        FormValidator.init();
        FormElements.init();
      });
    </script>
<% end %>

app/views/delivereds/edit.html.erb
					<div class="wrap-content container" id="container">
						<!-- start: PAGE TITLE -->
						<section id="page-title">
							<div class="row">
								<div class="col-sm-8">
									<h1 class="mainTitle">Form Ubah Delivered</h1>
									<span class="mainDescription">Form untuk menambah data Delivered yang baru</span>
								</div>
								<ol class="breadcrumb">
									<li>
										<span>Delivered Forms</span>
									</li>
									<li class="active">
										<span>Form Delivered</span>
									</li>
								</ol>
							</div>
						</section>
						<!-- end: PAGE TITLE -->
						<!-- start: BASIC EXAMPLE -->
						<div class="container-fluid container-fullw bg-white">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-lg-8 col-md-12">
											<div class="panel panel-white">
												<div class="panel-heading">
													<h5 class="panel-title">Form Ubah</h5>
												</div>
												<div class="panel-body">
													<%= render "form" %>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="row">
			                    <div class="col-md-12 space20">
			                    	<% 
				                      @not_authorized = true

				                      if current_user.user_group
				                        current_user.user_group.action_models.each do |action_model|
				                          if (action_model.controller_model.path == "admin/delivereds" && action_model.path == "show")
				                            @not_authorized = false
				                          end

				                          break if ! @not_authorized
				                        end
				                    end
				                  %>

				                  <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
				                      <a href="/delivereds/<%= params[:id] %>" class="btn btn-green">
				                        Show <i class="fa fa-search-plus"></i>
				                      </a>
				                  <% end %>
			                      <a href="/delivereds" class="btn btn-info">
			                        Back <i class="fa fa-reply"></i>
			                      </a>
			                    </div>
		                  	</div>
						</div>
						<!-- end: BASIC EXAMPLE -->
					</div>

app/views/delivereds/index.html.erb
					<div class="wrap-content container" id="container">
						<!-- start: PAGE TITLE -->
						<section id="page-title">
							<div class="row">
								<div class="col-sm-8">
									<h1 class="mainTitle">Kotak Masuk </h1>
									<span class="mainDescription"></span>
								</div>
								<ol class="breadcrumb">
									<li>
										<span>Delivered</span>
									</li>
									<li class="active">
										<span>Kotak Masuk</span>
									</li>
								</ol>
							</div>
						</section>
						<!-- end: PAGE TITLE -->
						<!-- start: DYNAMIC TABLE -->
						<div class="container-fluid container-fullw bg-white">
							<div class="row">
								<div class="col-md-12">
									<h5 class="over-title margin-bottom-15">List of <span class="text-bold">Delivered</span></h5>
									<div class="row">
					                    <div class="col-md-12 space20">
					                    	<% 
										        @not_authorized = true

										        if current_user.user_group
										          current_user.user_group.action_models.each do |action_model|
										            if (action_model.controller_model.path == "delivereds" && action_model.path == "new")
										              @not_authorized = false
										            end

										            break if ! @not_authorized
										          end
										      end
										    %>

										    <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
					                      	  	<a href="/delivereds/new" class="btn btn-green">
							                        Add New <i class="fa fa-plus"></i>
						                      	</a>
						                    <% end %>
					                    </div>
					                  </div>
									<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
										<thead>
											<tr>
												<th>Tanggal</th>
												<th>Pukul</th>
												<th>Nama Kurir</th>
												<th>Nama Penerima</th>
												<th>Aksi</th>
											</tr>
										</thead>
										<tbody>
											<% @delivereds.each do |delivered| %>
												<tr>
													<td><%= delivered.delivered_date ? delivered.delivered_date.strftime("%d/%m/%Y") : "N/A" %></td>
													<td><%= delivered.delivered_time ? delivered.delivered_time.strftime("%H:%M") : "N/A" %></td>
													<td><%= delivered.courier_name %></td>
													<td><%= delivered.receiver_name %></td>
													<td class="center">
													<div class="visible-md visible-lg hidden-sm hidden-xs">
														<%= link_to delivered_path(delivered) do %>
															<i class="fa fa-search"></i>
														<% end %>
														<% 
													        @not_authorized = true

													        if current_user.user_group
													          current_user.user_group.action_models.each do |action_model|
													            if (action_model.controller_model.path == "delivereds" && action_model.path == "edit")
													              @not_authorized = false
													            end

													            break if ! @not_authorized
													          end
													      end
													    %>
													    <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
															<%= link_to edit_delivered_path(delivered) do %>
																<i class="fa fa-edit"></i>
															<% end %>
														<% end %>

														<% 
													        @not_authorized = true

													        if current_user.user_group
													          current_user.user_group.action_models.each do |action_model|
													            if (action_model.controller_model.path == "delivereds" && action_model.path == "destroy")
													              @not_authorized = false
													            end

													            break if ! @not_authorized
													          end
													      end
													    %>
													    <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
															<%= link_to delivered_path(delivered), method: :delete, data: {confirm: "are you sure?"} do %>
																<i class="fa fa-trash"></i>
															<% end %>
														<% end %>
													</div>
													</td>
												</tr>
											<% end %>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<!-- end: DYNAMIC TABLE -->
						<!-- start: DYNAMIC TABLE -->
						
					</div>

			          <%= content_for :css do %>
			            <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
			            <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
			            <link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
			            <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
			          <% end %>

			          <%= content_for :js do %>
			            <script src="/vendor/select2/select2.min.js"></script>
			            <script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
			            <!-- start: JavaScript Event Handlers for this page -->
			            <script src="/assets/js/table-data.js"></script>
			            <script>
			              jQuery(document).ready(function() {
			                Main.init();
			                TableData.init();
			              });
			            </script>
			            <!-- end: JavaScript Event Handlers for this page -->
			          <% end %>

app/views/delivereds/new.html.erb
					<div class="wrap-content container" id="container">
						<!-- start: PAGE TITLE -->
						<section id="page-title">
							<div class="row">
								<div class="col-sm-8">
									<h1 class="mainTitle">Form Tambah Delivered</h1>
									<span class="mainDescription">Form untuk menambah data Delivered yang baru</span>
								</div>
								<ol class="breadcrumb">
									<li>
										<span>Delivered Forms</span>
									</li>
									<li class="active">
										<span>Form Delivered</span>
									</li>
								</ol>
							</div>
						</section>
						<!-- end: PAGE TITLE -->
						<!-- start: BASIC EXAMPLE -->
						<div class="container-fluid container-fullw bg-white">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="panel panel-white">
											<div class="panel-heading">
												<h5 class="panel-title">Form Tambah</h5>
											</div>
											<div class="panel-body">
												<%= render "form" %>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="row">
			                    <div class="col-md-12 space20">
			                      <a href="/package_statuses" class="btn btn-info">
			                        Back <i class="fa fa-reply"></i>
			                      </a>
			                    </div>
		                  	</div>
						</div>
						<!-- end: BASIC EXAMPLE -->
					</div>

app/views/delivereds/show.html.erb
  <div class="wrap-content container" id="container">
    <!-- start: PAGE TITLE -->
    <section id="page-title">
      <div class="row">
        <div class="col-sm-8">
          <h1 class="mainTitle">Delivered Data Detail</h1>
          <span class="mainDescription">Halaman untuk melihat detail inbound</span>
        </div>
        <ol class="breadcrumb">
          <li>
            <span>Delivered View</span>
          </li>
          <li class="active">
            <span>View Delivered</span>
          </li>
        </ol>
      </div>
    </section>
    <!-- end: PAGE TITLE -->
    <!-- start: BASIC EXAMPLE -->
    <div class="container-fluid container-fullw bg-white">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-lg-8 col-md-12">
              <div class="panel panel-white">
                <div class="panel-heading">
                  <h5 class="panel-title">Detail Delivered</h5>
                </div>
                <div class="panel-body">
                  <fieldset><legend>Paket</legend>
                    <table class="table">
                      <tbody>
                        <tr>
                          <td>Task ID</td>
                          <td><%= @inbound.inbound_number %></td>
                        </tr>
                        <tr>
                          <td>Tanggal Masuk</td>
                          <td><%= @inbound.inbound_date ? @inbound.inbound_date.strftime("%d/%m/%Y") : "" %> <%= @inbound.inbound_time ? @inbound.inbound_time.strftime("%H:%M") : "" %></td>
                        </tr>
                        <tr>
                          <td>Kurir</td>
                          <td><%= @inbound.courier ? @inbound.courier.name : "" %></td>
                        </tr>
                        <tr>
                          <td>Nomor Resi / AWB</td>
                          <td><%= @inbound.awb_number %></td>
                        </tr>
                        <tr>
                          <td>Tanggal Resi / AWB</td>
                          <td><%= @inbound.awb_date ? @inbound.awb_date.strftime("%d/%m/%Y") : "" %></td>
                        </tr>
                        <tr>
                          <td>Tipe Paket</td>
                          <td><%= @inbound.package_type ? @inbound.package_type.name : "N/A" %></td>
                        </tr>
                        <tr>
                          <td>Isi</td>
                          <td><%= @inbound.description %></td>
                        </tr>
                      </tbody>
                    </table>
                  </fieldset>
                  <fieldset><legend>Identitas Pengirim</legend>
                    <table class="table">
                      <tbody>
                        <tr>
                          <td>Nama Pengirim</td>
                          <td><%= @inbound.sender_name %></td>
                        </tr>
                        <tr>
                          <td>Departemen Pengirim</td>
                          <td><%= @inbound.sender_department %></td>
                        </tr>
                        <tr>
                          <td>Perusahaan Pengirim</td>
                          <td><%= @inbound.sender_company %></td>
                        </tr>
                      </tbody>
                    </table>
                  </fieldset>
                  <fieldset><legend>Identitas Penerima</legend>
                    <table class="table">
                      <tbody>
                        <tr>
                          <td>Nama Penerima</td>
                          <td><%= @inbound.user ? @inbound.user.name : "" %></td>
                        </tr>
                        <tr>
                          <td>Departemen Penerima</td>
                          <td><%= @inbound.department ? @inbound.department.name : "" %></td>
                        </tr>
                        <tr>
                          <td>Perusahaan Penerima</td>
                          <td><%= @inbound.company ? @inbound.company.name : "N/A" %></td>
                        </tr>
                      </tbody>
                    </table>
                  </fieldset>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
                <div class="col-md-12 space20">
                  <% 
                      @not_authorized = true

                      if current_user.user_group
                        current_user.user_group.action_models.each do |action_model|
                          if (action_model.controller_model.path == "admin/delivereds" && action_model.path == "edit")
                            @not_authorized = false
                          end

                          break if ! @not_authorized
                        end
                    end
                  %>

                  <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
                    <a href="/delivereds/<%= params[:id] %>/edit" class="btn btn-warning">
                      Edit <i class="fa fa-edit"></i>
                    </a>
                  <% end %>
                  <a href="/inbounds" class="btn btn-info">
                    Back <i class="fa fa-reply"></i>
                  </a>
                </div>
            </div>
    </div>
    <!-- end: BASIC EXAMPLE -->

    <!-- start: DYNAMIC TABLE -->
    <div class="container-fluid container-fullw">
      <div class="row">
        <div class="col-md-12">
          <h5 class="over-title margin-bottom-15">List of <span class="text-bold">Updates</span></h5>
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer" id="sample_1">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <% @inbound.inbound_statuses.each do |inbound_status| %>
                  <tr>
                    <td><%= inbound_status.created_at.strftime("%d-%m-%Y") %></td>
                    <td><%= inbound_status.package_status ? inbound_status.package_status.name : "N/A" %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= content_for :css do %>
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
  <% end %>

  <%= content_for :js do %>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/table-data.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        TableData.init();
      });
    </script>
    <!-- end: JavaScript Event Handlers for this page -->
  <% end %>