config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  root 'homes#index'

  post "json/departments/get_departments" => "departments#get_departments"
  post "json/users/get_users" => "users#get_users"
  post "json/package_types/get_package_types" => "package_types#get_package_types"
  post "json/inbounds/get_inbounds" => "inbounds#get_inbounds"

  get 'get_monthly_statistic' => "homes#get_monthly_statistic"

    resources :homes do 
      collection do
        get :unprocessed
        get :unprocessed_under_2_days
        get :unprocessed_2_5_days
        get :unprocessed_over_5_days
      end
    end
    resources :outbonds
    resources :inbounds do
      member do
        get :forward
        get :receive
      end
    end
    resources :internal_couriers
    resources :urgent_levels
    resources :with_couriers
    resources :delivereds
    resources :faileds
    resources :couriers
    resources :companies
    resources :users
    resources :user_groups
    resources :departments
    resources :controller_models
    resources :action_models
    resources :package_statuses
    resources :package_types
    resources :inbound_statuses
    resources :buildings
end

app/models/action_model.rb
class ActionModel < ActiveRecord::Base
	belongs_to :controller_model

	has_many :action_models_user_groups, dependent: :destroy
	has_many :user_groups, through: :action_models_user_groups
end

app/models/building.rb
class Building < ActiveRecord::Base
	has_many :companies, dependent: :destroy
	has_many :couriers, dependent: :destroy
	has_many :delivereds, dependent: :destroy
	has_many :departments, dependent: :destroy
	has_many :faileds, dependent: :destroy
	has_many :inbounds, dependent: :destroy
	has_many :internal_couriers, dependent: :destroy
	has_many :numbering_formats, dependent: :destroy
	has_many :urgent_levels, dependent: :destroy
	has_many :users, dependent: :destroy
	has_many :user_groups, dependent: :destroy
	has_many :with_couriers, dependent: :destroy
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :departments, dependent: :destroy
	has_many :users, dependent: :restrict_with_exception

	belongs_to :building
end

app/models/courier.rb
class Courier < ActiveRecord::Base

	belongs_to :building
end

app/models/delivered.rb
class Delivered < ActiveRecord::Base
	belongs_to :internal_courier

	belongs_to :building
end

app/models/department.rb
class Department < ActiveRecord::Base
	belongs_to :company

	belongs_to :building

	has_many :users, dependent: :restrict_with_exception
end

app/models/failed.rb
class Failed < ActiveRecord::Base
	belongs_to :internal_courier

	belongs_to :building
end

app/models/inbound.rb
class Inbound < ActiveRecord::Base
	belongs_to :company
	belongs_to :user
	belongs_to :department
	belongs_to :created, class_name: "User", foreign_key: "created_by"
	belongs_to :package_type
	belongs_to :courier
	belongs_to :urgent_level
	belongs_to :with_courier
	belongs_to :delivered
	belongs_to :failed

	has_many :inbound_statuses, dependent: :destroy

	belongs_to :building
end

app/models/inbound_status.rb
class InboundStatus < ActiveRecord::Base
	belongs_to :package_status
	belongs_to :inbound
end

app/models/outbound.rb
class Outbound < ActiveRecord::Base
	belongs_to :company
	belongs_to :user
	belongs_to :department
	belongs_to :created, class_name: "User", foreign_key: "created_by"
	belongs_to :package_type
end

app/models/package_status.rb
class PackageStatus < ActiveRecord::Base
end

app/models/package_type.rb
class PackageType < ActiveRecord::Base
	has_many :inbounds, dependent: :restrict_with_exception
	has_many :outbounds, dependent: :restrict_with_exception
end

app/models/urgent_level.rb
class UrgentLevel < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable 

  belongs_to :user_group
  belongs_to :company
  belongs_to :department

  belongs_to :building

  has_many :inbounds, dependent: :restrict_with_exception

  # paperclip

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/missing.png",
    :url => '/images/users/:basename_:style_:id.:extension',
    :path => ":rails_root/public/images/users/:basename_:style_:id.:extension"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
	has_many :users, dependent: :restrict_with_exception

	has_many :action_models_user_groups, dependent: :destroy
	has_many :action_models, through: :action_models_user_groups

	belongs_to :building
end

app/models/with_courier.rb
class WithCourier < ActiveRecord::Base
	belongs_to :internal_courier

	belongs_to :building
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorize_user

    def index
      if current_user.building
        @companies = Company.where("building_id = ?", current_user.building_id).order("created_at DESC")
      else
        @companies = Company.order("created_at DESC")
      end
    end

    def new
      @company = Company.new
      
      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @companies }
      end
    end

    def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @companies }
    end
  end
  
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save        
        format.html { redirect_to(company_path(@company.id), :notice => 'Company was successfully created.') }
        format.xml  { render :xml => @company, :status => :created, :company => @company }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def edit
    @company = Company.find(params[:id])
  end
  
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(company_params)        
        format.html { redirect_to(company_path(@company), :notice => 'Company was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to(:controller => 'companies') }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def company_params
    params.require(:company).permit(:created_by, :description, :name, :updated_by, :building_id)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/faileds_helper.rb
module FailedsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inbounds_helper.rb
module InboundsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company, html: {class: "form-horizontal"}) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:action] == "new" %>
      <%= f.hidden_field :created_by, :value => current_user.id %>
    <% else %>
      <%= f.hidden_field :updated_by, :value => current_user.id %>
    <% end %>

    <% if current_user.building %>
      <%= f.hidden_field :building_id, :value => current_user.building_id %>
    <% end %>

  <div class="form-group">
    <label class="col-sm-3 control-label">
      Name
    </label>
    <div class="col-sm-7">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter name ..' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">
      Description
    </label>
    <div class="col-sm-7">
      <%= f.text_area :description, class: "form-control", placeholder: "Enter description .." %>
    </div>
  </div>
  <button type="submit" class="btn btn-o btn-primary">
    Submit
  </button>
<% end %>

<%= content_for :css do %>
  
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link href="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<% end %>

<%= content_for :js do %>
    
    <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <script src="/vendor/ckeditor/ckeditor.js"></script>
    <script src="/vendor/ckeditor/adapters/jquery.js"></script>
    <script src="/vendor/jquery-validation/jquery.validate.min.js"></script>

    <script src="/vendor/maskedinput/jquery.maskedinput.min.js"></script>
    <script src="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <script src="/vendor/autosize/autosize.min.js"></script>
    <script src="/vendor/selectFx/classie.js"></script>
    <script src="/vendor/selectFx/selectFx.js"></script>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
    <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
  
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/form-validation.js"></script>
    <script src="/assets/js/form-elements.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        FormValidator.init();
        FormElements.init();
      });
    </script>
<% end %>

app/views/companies/edit.html.erb
					<div class="wrap-content container" id="container">
						<!-- start: PAGE TITLE -->
						<section id="page-title">
							<div class="row">
								<div class="col-sm-8">
									<h1 class="mainTitle">Form Ubah Company</h1>
									<span class="mainDescription">Form untuk menambah data Company yang baru</span>
								</div>
								<ol class="breadcrumb">
									<li>
										<span>Company Forms</span>
									</li>
									<li class="active">
										<span>Form Company</span>
									</li>
								</ol>
							</div>
						</section>
						<!-- end: PAGE TITLE -->
						<!-- start: BASIC EXAMPLE -->
						<div class="container-fluid container-fullw bg-white">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-lg-8 col-md-12">
											<div class="panel panel-white">
												<div class="panel-heading">
													<h5 class="panel-title">Form Ubah</h5>
												</div>
												<div class="panel-body">
													<%= render "form" %>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="row">
			                    <div class="col-md-12 space20">
			                    	<% 
					                    @not_authorized = true

					                    if current_user.user_group
					                      current_user.user_group.action_models.each do |action_model|
					                        if (action_model.controller_model.path == "admin/companies" && action_model.path == "show")
					                          @not_authorized = false
					                        end

					                        break if ! @not_authorized
					                      end
					                  end
					                %>

					                <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
				                      <a href="/companies/<%= params[:id] %>" class="btn btn-green">
				                        Show <i class="fa fa-search-plus"></i>
				                      </a>
				                    <% end %>

				                    <% 
					                    @not_authorized = true

					                    if current_user.user_group
					                      current_user.user_group.action_models.each do |action_model|
					                        if (action_model.controller_model.path == "admin/companies" && action_model.path == "index")
					                          @not_authorized = false
					                        end

					                        break if ! @not_authorized
					                      end
					                  end
					                %>

					                <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
				                      <a href="/companies" class="btn btn-info">
				                        Back <i class="fa fa-reply"></i>
				                      </a>
				                    <% end %>
			                    </div>
		                  	</div>
						</div>
						<!-- end: BASIC EXAMPLE -->
					</div>

app/views/companies/index.html.erb
          <div class="wrap-content container" id="container">
            <!-- start: PAGE TITLE -->
            <section id="page-title">
              <div class="row">
                <div class="col-sm-8">
                  <h1 class="mainTitle">COMPANY LIST</h1>
                  <span class="mainDescription">Halaman untuk menampilkan daftar Company</span>
                </div>
                <ol class="breadcrumb">
                  <li>
                    <span>Dashboard</span>
                  </li>
                  <li class="active">
                    <span>Company List</span>
                  </li>
                </ol>
              </div>
            </section>
            <!-- end: PAGE TITLE -->
            <!-- start: DYNAMIC TABLE -->
            <div class="container-fluid container-fullw">
              <div class="row">
                <div class="col-md-12">
                  <h5 class="over-title margin-bottom-15">List of <span class="text-bold">Companies</span></h5>
                  <div class="row">
                    <div class="col-md-12 space20">
                      <% 
                            @not_authorized = true

                            if current_user.user_group
                              current_user.user_group.action_models.each do |action_model|
                                if (action_model.controller_model.path == "companies" && action_model.path == "new")
                                  @not_authorized = false
                                end

                                break if ! @not_authorized
                              end
                          end
                        %>

                        <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
                                      <a href="/companies/new" class="btn btn-green">
                                      Add New <i class="fa fa-plus"></i>
                                    </a>
                                <% end %>
                    </div>
                  </div>
                  <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer" id="sample_1">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Description</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @companies.each do |company| %>
                          <tr>
                            <td><%= link_to company.name, company_path(company) %></td>
                            <td><%= company.description %></td>
                            <td>
                              <% 
                                  @not_authorized = true

                                  if current_user.user_group
                                    current_user.user_group.action_models.each do |action_model|
                                      if (action_model.controller_model.path == "companies" && action_model.path == "edit")
                                        @not_authorized = false
                                      end

                                      break if ! @not_authorized
                                    end
                                end
                              %>

                              <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
                                <%= link_to edit_company_path(company) do %>
                                  <i class="fa fa-edit"></i>
                                <% end %>
                              <% end %>

                              <% 
                                  @not_authorized = true

                                  if current_user.user_group
                                    current_user.user_group.action_models.each do |action_model|
                                      if (action_model.controller_model.path == "companies" && action_model.path == "destroy")
                                        @not_authorized = false
                                      end

                                      break if ! @not_authorized
                                    end
                                end
                              %>

                              <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
                                <%= link_to company_path(company), method: :delete, data: {confirm: "are you sure?"} do %>
                                  <i class="fa fa-trash"></i>
                                <% end %>
                              <% end %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <%= content_for :css do %>
            <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
            <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
            <link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
            <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
          <% end %>

          <%= content_for :js do %>
            <script src="/vendor/select2/select2.min.js"></script>
            <script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
            <!-- start: JavaScript Event Handlers for this page -->
            <script src="/assets/js/table-data.js"></script>
            <script>
              jQuery(document).ready(function() {
                Main.init();
                TableData.init();
              });
            </script>
            <!-- end: JavaScript Event Handlers for this page -->
          <% end %>

app/views/companies/new.html.erb
					<div class="wrap-content container" id="container">
						<!-- start: PAGE TITLE -->
						<section id="page-title">
							<div class="row">
								<div class="col-sm-8">
									<h1 class="mainTitle">Form Tambah Company</h1>
									<span class="mainDescription">Form untuk menambah data Company yang baru</span>
								</div>
								<ol class="breadcrumb">
									<li>
										<span>Company Forms</span>
									</li>
									<li class="active">
										<span>Form Company</span>
									</li>
								</ol>
							</div>
						</section>
						<!-- end: PAGE TITLE -->
						<!-- start: BASIC EXAMPLE -->
						<div class="container-fluid container-fullw bg-white">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-lg-8 col-md-12">
											<div class="panel panel-white">
												<div class="panel-heading">
													<h5 class="panel-title">Form Tambah</h5>
												</div>
												<div class="panel-body">
													<%= render "form" %>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="row">
			                    <div class="col-md-12 space20">
			                      <a href="/companies" class="btn btn-info">
			                        Back <i class="fa fa-reply"></i>
			                      </a>
			                    </div>
		                  	</div>
						</div>
						<!-- end: BASIC EXAMPLE -->
					</div>

app/views/companies/show.html.erb
  <div class="wrap-content container" id="container">
    <!-- start: PAGE TITLE -->
    <section id="page-title">
      <div class="row">
        <div class="col-sm-8">
          <h1 class="mainTitle">Company Data Detail</h1>
          <span class="mainDescription">Halaman untuk melihat detail company</span>
        </div>
        <ol class="breadcrumb">
          <li>
            <span>Company View</span>
          </li>
          <li class="active">
            <span>View Company</span>
          </li>
        </ol>
      </div>
    </section>
    <!-- end: PAGE TITLE -->
    <!-- start: BASIC EXAMPLE -->
    <div class="container-fluid container-fullw bg-white">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-lg-8 col-md-12">
              <div class="panel panel-white">
                <div class="panel-heading">
                  <h5 class="panel-title">Detail Company</h5>
                </div>
                <div class="panel-body">
                  <table class="table">
                    <tbody>
                      <tr>
                        <td>Name</td>
                        <td><%= @company.name %></td>
                      </tr>
                      <tr>
                        <td>Description</td>
                        <td><%= @company.description %></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
                <div class="col-md-12 space20">
                  <% 
                      @not_authorized = true

                      if current_user.user_group
                        current_user.user_group.action_models.each do |action_model|
                          if (action_model.controller_model.path == "admin/companies" && action_model.path == "edit")
                            @not_authorized = false
                          end

                          break if ! @not_authorized
                        end
                    end
                  %>

                  <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
                    <a href="/companies/<%= params[:id] %>/edit" class="btn btn-warning">
                      Edit <i class="fa fa-edit"></i>
                    </a>
                  <% end %>

                  <% 
                      @not_authorized = true

                      if current_user.user_group
                        current_user.user_group.action_models.each do |action_model|
                          if (action_model.controller_model.path == "admin/companies" && action_model.path == "index")
                            @not_authorized = false
                          end

                          break if ! @not_authorized
                        end
                    end
                  %>

                  <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
                    <a href="/companies" class="btn btn-info">
                      Back <i class="fa fa-reply"></i>
                    </a>
                  <% end %>
                </div>
            </div>
    </div>
    <!-- end: BASIC EXAMPLE -->

    <!-- start: DYNAMIC TABLE -->
    <div class="container-fluid container-fullw">
      <div class="row">
        <div class="col-md-12">
          <h5 class="over-title margin-bottom-15">List of <span class="text-bold">Departments</span></h5>
          <div class="row">
            <div class="col-md-12 space20">
              <a href="/departments/new?company_id=<%= params[:id] %>" class="btn btn-green">
                Add New <i class="fa fa-plus"></i>
              </a>
            </div>
          </div>
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer" id="sample_1">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <% @company.departments.each do |department| %>
                  <tr>
                    <td><%= link_to department.name, department_path(department) %></td>
                    <td><%= department.description %></td>
                    <td>
                      <% 
                          @not_authorized = true

                          if current_user.user_group
                            current_user.user_group.action_models.each do |action_model|
                              if (action_model.controller_model.path == "admin/departments" && action_model.path == "edit")
                                @not_authorized = false
                              end

                              break if ! @not_authorized
                            end
                        end
                      %>

                      <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
                        <%= link_to image_tag("skin/edit_16.png"), edit_department_path(department) %>
                      <% end %>

                      <% 
                          @not_authorized = true

                          if current_user.user_group
                            current_user.user_group.action_models.each do |action_model|
                              if (action_model.controller_model.path == "admin/departments" && action_model.path == "destroy")
                                @not_authorized = false
                              end

                              break if ! @not_authorized
                            end
                        end
                      %>

                      <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
                        <%= link_to image_tag("skin/delete_16.png"), department_path(department), :confirm => 'Are you sure?', :method => :delete, :class => 'del' %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= content_for :css do %>
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
  <% end %>

  <%= content_for :js do %>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/table-data.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        TableData.init();
      });
    </script>
    <!-- end: JavaScript Event Handlers for this page -->
  <% end %>