config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  root 'homes#index'

  post "json/departments/get_departments" => "departments#get_departments"
  post "json/users/get_users" => "users#get_users"
  post "json/package_types/get_package_types" => "package_types#get_package_types"
  post "json/inbounds/get_inbounds" => "inbounds#get_inbounds"

  get 'get_monthly_statistic' => "homes#get_monthly_statistic"

    resources :homes do 
      collection do
        get :unprocessed
        get :unprocessed_under_2_days
        get :unprocessed_2_5_days
        get :unprocessed_over_5_days
      end
    end
    resources :outbonds
    resources :inbounds do
      member do
        get :forward
        get :receive
      end
    end
    resources :internal_couriers
    resources :urgent_levels
    resources :with_couriers
    resources :delivereds
    resources :faileds
    resources :couriers
    resources :companies
    resources :users
    resources :user_groups
    resources :departments
    resources :controller_models
    resources :action_models
    resources :package_statuses
    resources :package_types
    resources :inbound_statuses
    resources :buildings
end

app/models/with_courier.rb
class WithCourier < ActiveRecord::Base
	belongs_to :internal_courier

	belongs_to :building
end

app/controllers/with_couriers_controller.rb
class WithCouriersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorize_user

  def index
    @with_couriers = WithCourier.order("created_at DESC")
  end

  def new
    @with_courier = WithCourier.new
    if current_user.building
      @internal_couriers = current_user.building.internal_couriers
      @inbounds = Inbound.where(inbound_status: 1, building_id: current_user.building_id)
    else
      @internal_couriers = InternalCourier.all
      @inbounds = Inbound.where(inbound_status: 1)
    end
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @inbounds }
    end
  end

  def show
    @with_courier = WithCourier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @inbounds }
    end
  end

  def create
    @with_courier = WithCourier.new(with_courier_params)
    internal_couriers = InternalCourier.find(params[:with_courier][:internal_courier_id])
    @with_courier.courier_name = internal_couriers.name

    if current_user.building
      @internal_couriers = current_user.building.internal_couriers
      @inbounds = Inbound.where(inbound_status: 1, building_id: current_user.building_id)
    else
      @internal_couriers = InternalCourier.all
      @inbounds = Inbound.where(inbound_status: 1)
    end

    respond_to do |format|
      if @with_courier.save 
        id_inbounds = params[:inbounds]
        id_inbounds.each do |id|
          inbound = Inbound.find(id)
          inbound.with_courier_id = @with_courier.id
          inbound.with_courier_date = @with_courier.with_courier_date
          inbound.with_courier_time = @with_courier.with_courier_time
          inbound.inbound_status = 2
          inbound.save
        end

        format.html { redirect_to(with_couriers_path, :notice => 'Inbound was successfully created.') }
        format.xml  { render :xml => @inbound, :status => :created, :inbound => @inbound }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @inbound.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @with_courier = WithCourier.find(params[:id])
    if current_user.building
      @internal_couriers = current_user.building.internal_couriers
      @inbounds = Inbound.where(inbound_status: 1, building_id: current_user.building_id)
    else
      @internal_couriers = InternalCourier.all
      @inbounds = Inbound.where(inbound_status: 1)
    end
  end
  
  def update
    @with_courier = WithCourier.find(params[:id])

    if current_user.building
      @internal_couriers = current_user.building.internal_couriers
      @inbounds = Inbound.where(inbound_status: 1, building_id: current_user.building_id)
    else
      @internal_couriers = InternalCourier.all
      @inbounds = Inbound.where(inbound_status: 1)
    end

    inbounds = Inbound.where(with_courier_id: params[:id])
    inbounds.each do |inbound|
      inbound.with_courier_id = nil
      inbound.with_courier_date = nil
      inbound.with_courier_time = nil
      inbound.inbound_status = 1
      inbound.save
    end

    respond_to do |format|
      internal_couriers = InternalCourier.find(params[:with_courier][:internal_courier_id])
      params[:with_courier][:courier_name] = internal_couriers.name
      if @with_courier.update_attributes(with_courier_params)
        id_inbounds = params[:inbounds]
        id_inbounds.each do |id|
          inbound = Inbound.find(id)
          inbound.with_courier_id = @with_courier.id
          inbound.with_courier_date = @with_courier.with_courier_date
          inbound.with_courier_time = @with_courier.with_courier_time
          inbound.inbound_status = 2
          inbound.save
        end 
        format.html { redirect_to(with_courier_path(@with_courier), :notice => 'Inbound was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @with_courier.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @with_courier = WithCourier.find(params[:id])
    @with_courier.destroy

    respond_to do |format|
      format.html { redirect_to(:controller => 'inbounds') }
      format.xml  { head :ok }
    end
  end

  private
  def with_courier_params
    params.require(:with_courier).permit(:with_courier_date, :with_courier_time, :courier_name, :internal_courier_id, :building_id)
  end
end

app/helpers/with_couriers_helper.rb
module WithCouriersHelper
end

app/views/with_couriers/_form.html.erb
<%= form_for(@with_courier, html: {class: "form-horizontal", role: "form"}) do |f| %>
  <% if @with_courier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@with_courier.errors.count, "error") %> prohibited this with_courier from being saved:</h2>

      <ul>
      <% @with_courier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:action] == "new" %>
      <%= f.hidden_field :created_by, :value => current_user.id %>
    <% else %>
      <%= f.hidden_field :updated_by, :value => current_user.id %>
    <% end %>

    <% if current_user.building %>
      <%= f.hidden_field :building_id, :value => current_user.building_id %>
    <% end %>

    <fieldset>
      <legend>Paket</legend>
      <div class="form-group">
        <label class="col-sm-3 control-label" for="date">
          Tanggal Diambil Kurir
        </label>
        <div class="col-sm-7">
          <div class="col-sm-6 padding-left-0">
            <input name="with_courier[with_courier_date]" value="<%= @with_courier.with_courier_date %>" class="col-sm-3 form-control format-datepicker" placeholder="choose the date here .." type="text">
          </div>
          <div class="col-sm-6 padding-right-0">
            <input type="text" name="with_courier[with_courier_time]" value="<%= @with_courier.with_courier_time %>" id="timepicker-default" class="col-sm-3 form-control" placeholder="choose the time here ..">
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <label class="col-sm-3 control-label" for="idfield">
          Internal Courier
        </label>
        <div class="col-sm-7">
          <%= f.select :internal_courier_id, options_from_collection_for_select(@internal_couriers, "id", "name", @with_courier.internal_courier_id), {include_blank: "-- Pilih Kurir Internal --"}, {class: "js-example-placeholder-single js-states form-control"} %>
        </div>
      </div>  

      <div class="form-group">
        <label class="col-sm-3 control-label" for="idfield">
            Paket
        </label>
        <div class="col-sm-7">
            <select name='inbounds[]' multiple class="js-example-basic-multiple js-states form-control">
              <% @inbounds.each do |inbound| %>
                <option value="<%= inbound.id %>"><%= inbound.awb_number %></option>
              <% end %>
            </select>
        </div>
      </div>
    </fieldset>

    <div class="form-group margin-bottom-0">
      <div class="col-sm-offset-3 col-sm-9">
        <button type="submit" class="btn btn-primary margin-left-15">
          Submit
        </button>
      </div>
    </div>
<% end %>

<%= content_for :css do %>
  
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link href="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<% end %>

<%= content_for :js do %>
    
    <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <script src="/vendor/ckeditor/ckeditor.js"></script>
    <script src="/vendor/ckeditor/adapters/jquery.js"></script>
    <script src="/vendor/jquery-validation/jquery.validate.min.js"></script>

    <script src="/vendor/maskedinput/jquery.maskedinput.min.js"></script>
    <script src="/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <script src="/vendor/autosize/autosize.min.js"></script>
    <script src="/vendor/selectFx/classie.js"></script>
    <script src="/vendor/selectFx/selectFx.js"></script>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
    <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
  
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/form-validation.js"></script>
    <script src="/assets/js/form-elements.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        FormValidator.init();
        FormElements.init();
      });
    </script>
<% end %>

app/views/with_couriers/edit.html.erb
					<div class="wrap-content container" id="container">
						<!-- start: PAGE TITLE -->
						<section id="page-title">
							<div class="row">
								<div class="col-sm-8">
									<h1 class="mainTitle">Form Ubah With Courier</h1>
									<span class="mainDescription">Form untuk menambah data With Courier yang baru</span>
								</div>
								<ol class="breadcrumb">
									<li>
										<span>With Courier Forms</span>
									</li>
									<li class="active">
										<span>Form With Courier</span>
									</li>
								</ol>
							</div>
						</section>
						<!-- end: PAGE TITLE -->
						<!-- start: BASIC EXAMPLE -->
						<div class="container-fluid container-fullw bg-white">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-lg-8 col-md-12">
											<div class="panel panel-white">
												<div class="panel-heading">
													<h5 class="panel-title">Form Ubah</h5>
												</div>
												<div class="panel-body">
													<%= render "form" %>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="row">
			                    <div class="col-md-12 space20">
			                      <% 
				                      @not_authorized = true

				                      if current_user.user_group
				                        current_user.user_group.action_models.each do |action_model|
				                          if (action_model.controller_model.path == "admin/with_couriers" && action_model.path == "edit")
				                            @not_authorized = false
				                          end

				                          break if ! @not_authorized
				                        end
				                    end
				                  %>

				                  <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
				                      <a href="/with_couriers/<%= params[:id] %>" class="btn btn-green">
				                        Show <i class="fa fa-search-plus"></i>
				                      </a>
				                  <% end %>
			                      <a href="/with_couriers" class="btn btn-info">
			                        Back <i class="fa fa-reply"></i>
			                      </a>
			                    </div>
		                  	</div>
						</div>
						<!-- end: BASIC EXAMPLE -->
					</div>

app/views/with_couriers/index.html.erb
					<div class="wrap-content container" id="container">
						<!-- start: PAGE TITLE -->
						<section id="page-title">
							<div class="row">
								<div class="col-sm-8">
									<h1 class="mainTitle">Kotak Masuk </h1>
									<span class="mainDescription"></span>
								</div>
								<ol class="breadcrumb">
									<li>
										<span>With Courier</span>
									</li>
									<li class="active">
										<span>Kotak Masuk</span>
									</li>
								</ol>
							</div>
						</section>
						<!-- end: PAGE TITLE -->
						<!-- start: DYNAMIC TABLE -->
						<div class="container-fluid container-fullw bg-white">
							<div class="row">
								<div class="col-md-12">
									<h5 class="over-title margin-bottom-15">List of <span class="text-bold">With Couriers</span></h5>
									<div class="row">
					                    <div class="col-md-12 space20">
					                    	<% 
										        @not_authorized = true

										        if current_user.user_group
										          current_user.user_group.action_models.each do |action_model|
										            if (action_model.controller_model.path == "with_couriers" && action_model.path == "new")
										              @not_authorized = false
										            end

										            break if ! @not_authorized
										          end
										      end
										    %>

										    <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
					                      	  	<a href="/with_couriers/new" class="btn btn-green">
							                        Add New <i class="fa fa-plus"></i>
						                      	</a>
						                    <% end %>
					                    </div>
					                  </div>
									<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
										<thead>
											<tr>
												<th>Tanggal</th>
												<th>Pukul</th>
												<th>Nama Kurir</th>
												<th>Aksi</th>
											</tr>
										</thead>
										<tbody>
											<% @with_couriers.each do |with_courier| %>
												<tr>
													<td><%= with_courier.with_courier_date ? with_courier.with_courier_date.strftime("%d/%m/%Y") : "N/A" %></td>
													<td><%= with_courier.with_courier_time ? with_courier.with_courier_time.strftime("%H:%M") : "N/A" %></td>
													<td><%= with_courier.courier_name %></td>
													<td class="center">
													<div class="visible-md visible-lg hidden-sm hidden-xs">
														<%= link_to with_courier_path(with_courier) do %>
															<i class="fa fa-search"></i>
														<% end %>
														<% 
													        @not_authorized = true

													        if current_user.user_group
													          current_user.user_group.action_models.each do |action_model|
													            if (action_model.controller_model.path == "with_couriers" && action_model.path == "edit")
													              @not_authorized = false
													            end

													            break if ! @not_authorized
													          end
													      end
													    %>
													    <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
															<%= link_to edit_with_courier_path(with_courier) do %>
																<i class="fa fa-edit"></i>
															<% end %>
														<% end %>

														<% 
													        @not_authorized = true

													        if current_user.user_group
													          current_user.user_group.action_models.each do |action_model|
													            if (action_model.controller_model.path == "with_couriers" && action_model.path == "destroy")
													              @not_authorized = false
													            end

													            break if ! @not_authorized
													          end
													      end
													    %>
													    <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
															<%= link_to with_courier_path(with_courier), method: :delete, data: {confirm: "are you sure?"} do %>
																<i class="fa fa-trash"></i>
															<% end %>
														<% end %>
													</div>
													</td>
												</tr>
											<% end %>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<!-- end: DYNAMIC TABLE -->
						<!-- start: DYNAMIC TABLE -->
						
					</div>

			          <%= content_for :css do %>
			            <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
			            <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
			            <link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
			            <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
			          <% end %>

			          <%= content_for :js do %>
			            <script src="/vendor/select2/select2.min.js"></script>
			            <script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
			            <!-- start: JavaScript Event Handlers for this page -->
			            <script src="/assets/js/table-data.js"></script>
			            <script>
			              jQuery(document).ready(function() {
			                Main.init();
			                TableData.init();
			              });
			            </script>
			            <!-- end: JavaScript Event Handlers for this page -->
			          <% end %>

app/views/with_couriers/new.html.erb
					<div class="wrap-content container" id="container">
						<!-- start: PAGE TITLE -->
						<section id="page-title">
							<div class="row">
								<div class="col-sm-8">
									<h1 class="mainTitle">Form Tambah With Courier</h1>
									<span class="mainDescription">Form untuk menambah data With Courier yang baru</span>
								</div>
								<ol class="breadcrumb">
									<li>
										<span>With Courier Forms</span>
									</li>
									<li class="active">
										<span>Form With Courier</span>
									</li>
								</ol>
							</div>
						</section>
						<!-- end: PAGE TITLE -->
						<!-- start: BASIC EXAMPLE -->
						<div class="container-fluid container-fullw bg-white">
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="panel panel-white">
											<div class="panel-heading">
												<h5 class="panel-title">Form Tambah</h5>
											</div>
											<div class="panel-body">
												<%= render "form" %>
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="row">
			                    <div class="col-md-12 space20">
			                      <a href="/with_couriers" class="btn btn-info">
			                        Back <i class="fa fa-reply"></i>
			                      </a>
			                    </div>
		                  	</div>
						</div>
						<!-- end: BASIC EXAMPLE -->
					</div>

app/views/with_couriers/show.html.erb
  <div class="wrap-content container" id="container">
    <!-- start: PAGE TITLE -->
    <section id="page-title">
      <div class="row">
        <div class="col-sm-8">
          <h1 class="mainTitle">With Courier Data Detail</h1>
          <span class="mainDescription">Halaman untuk melihat detail inbound</span>
        </div>
        <ol class="breadcrumb">
          <li>
            <span>With Courier View</span>
          </li>
          <li class="active">
            <span>View With Courier</span>
          </li>
        </ol>
      </div>
    </section>
    <!-- end: PAGE TITLE -->
    <!-- start: BASIC EXAMPLE -->
    <div class="container-fluid container-fullw bg-white">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-lg-8 col-md-12">
              <div class="panel panel-white">
                <div class="panel-heading">
                  <h5 class="panel-title">Detail With Courier</h5>
                </div>
                <div class="panel-body">
                  <fieldset><legend>With Courier</legend>
                    <table class="table">
                      <tbody>
                        <tr>
                          <td>Tanggal With Courier</td>
                          <td><%= @with_courier.with_courier_date %></td>
                        </tr>
                        <tr>
                          <td>Jam With Courier</td>
                          <td><%= @with_courier.with_courier_time %></td>
                        </tr>
                        <tr>
                          <td>Nama Kurir</td>
                          <td><%= @with_courier.courier_name %></td>
                        </tr>

                      </tbody>
                    </table>
                  </fieldset>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
                <div class="col-md-12 space20">
                  <% 
                      @not_authorized = true

                      if current_user.user_group
                        current_user.user_group.action_models.each do |action_model|
                          if (action_model.controller_model.path == "admin/with_couriers" && action_model.path == "edit")
                            @not_authorized = false
                          end

                          break if ! @not_authorized
                        end
                    end
                  %>

                  <% if ! @not_authorized || (current_user.user_group && current_user.user_group.super == 1) %>
                    <a href="/with_couriers/<%= params[:id] %>/edit" class="btn btn-warning">
                      Edit <i class="fa fa-edit"></i>
                    </a>
                  <% end %>
                  <a href="/with_couriers" class="btn btn-info">
                    Back <i class="fa fa-reply"></i>
                  </a>
                </div>
            </div>
    </div>
    <!-- end: BASIC EXAMPLE -->

  </div>

  <%= content_for :css do %>
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="/vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
  <% end %>

  <%= content_for :js do %>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/DataTables/jquery.dataTables.min.js"></script>
    <!-- start: JavaScript Event Handlers for this page -->
    <script src="/assets/js/table-data.js"></script>
    <script>
      jQuery(document).ready(function() {
        Main.init();
        TableData.init();
      });
    </script>
    <!-- end: JavaScript Event Handlers for this page -->
  <% end %>